name: Pipeline CI/CD

on:
  schedule:
    - cron: '10 00 * * *'  # Executa todos os dias às 8h da manhã (UTC)
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: [self-hosted, devsecops]       # Seleciona os Self-Hosted Runners através de suas labels (pode ser também runners hospedados pelo github: ubuntu-latest, windows-latest, macos-latest)
    steps:
      - name: Compilar
        run: echo "Buildando o projeto"

  deploy:
    needs: build                            # Esse Job apenas será executado se o anterior executar com sucesso
    runs-on: [self-hosted, devsecops]       # Seleciona os Self-Hosted Runners através de suas labels (pode ser também runners hospedados pelo github: ubuntu-latest, windows-latest, macos-latest)
    steps:
      - name: Deploy
        run: echo "Fazendo deploy"
