name: CD - Deploy Development

on:
  workflow_run:
    workflows: ["Pipeline CI"]  # Nome do workflow do CI (deve bater exatamente)
    types:
      - completed
      
jobs:
  deploy:
    runs-on: [self-hosted, devsecops]
    environment: development
    steps:
      - name: Baixar artefato com a tag da imagem
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Ler a tag da imagem
        id: read_tag
        run: |
          TAG=$(cat tag.txt)
          echo "tag_name=$TAG" >> $GITHUB_OUTPUT

      - name: Realizar Deploy
        run: |
          echo "Realizando Deploy da imagem: ghcr.io/${{ github.repository_owner }}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.read_tag.outputs.tag_name }}"
    
      # - name: Login no Azure (AKS)
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Obter contexto do AKS
      #   uses: azure/aks-set-context@v3
      #   with:
      #     resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
      #     cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}

      # - name: Aplicar imagem no deployment
      #   run: |
      #     kubectl set image deployment/my-deployment \
      #       my-container=ghcr.io/${{ github.repository_owner }}/myapp:${{ inputs.image_tag }} \
      #       --namespace=development

      # - name: Verificar rollout
      #   run: |
      #     kubectl rollout status deployment/my-deployment --namespace=development
