name: CD - Deploy Production

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag da imagem Docker publicada no GHCR'
        required: true
        
env:
  TARGET: 'http://localhost:3000' # Alterar para a URL da aplicação
  DOCKER_IMAGE_NAME: devsecops
  
jobs:
  deploy_and_dast:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Realizar Deploy
        run: echo "Realizando Deploy..."
        
      - name: Checkout do código (se necessário)
        uses: actions/checkout@v3
        
      - name: Login no GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Definir REPO_OWNER e TAG_NAME
        run: |
          echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "TAG_NAME=${{ inputs.TAG_NAME }}" >> $GITHUB_ENV

      # Conecta no EC2 da AWS via SSH e faz o deploy da aplicação na máquina
      - name: Deploy APP
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ env.target }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/"$REPO_OWNER"/"$DOCKER_IMAGE_NAME":"$TAG_NAME"
            
            echo "Verificando se o container já existe..."
            if [ "$(docker ps -aq -f name="$DOCKER_IMAGE_NAME")" ]; then
              echo "Parando e removendo container existente..."
              docker stop meu-app
              docker rm meu-app
            else
              echo "Nenhum container existente encontrado."
            fi
            
            echo "Iniciando novo container..."
            docker run -d --name $DOCKER_IMAGE_NAME -p 3000:3000 ghcr.io/"$REPO_OWNER"/"$DOCKER_IMAGE_NAME":"$TAG_NAME"

      - name: Nuclei - Vulnerability Scan
        uses: projectdiscovery/nuclei-action@main
        with:
          target: ${{ env.target }}
          github-report: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # O upload só deve ocorrer se o SARIF existir (opcional)
      # - name: GitHub Security Dashboard Alerts update
      #   continue-on-error: true
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: nuclei.sarif
            
      - name: Executar ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ env.target }}
