name: CD - Deploy Staging

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag da imagem Docker publicada no GHCR'
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, devsecops]
    environment: staging
    steps:
      - name: Realizar Deploy
        run: echo "Realizando Deploy..."
        
  dast:
      runs-on: ubuntu-latest
      needs: deploy
      steps:
        - name: Nuclei - Vulnerability Scan
          uses: projectdiscovery/nuclei-action@main
          with:
              target: ${{secrets.AWS_SERVER_IP}}
              github-report: true
              github-token: ${{ secrets.GITHUB_TOKEN }}
  
    
        - name: GitHub Security Dashboard Alerts update
          uses: github/codeql-action/upload-sarif@v3
          with:
              sarif_file: nuclei.sarif
              
